[package]
name = "risp"
version = "1.1.0"
authors = ["Fumi Kanari <expugnatiomundi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
