[package]
name = "risp"
version = "1.2.0"
authors = ["ShrimpF <fkforgit2323@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
